### ISSUE TITLE
Support for more than 1 parameter

### ISSUE THREAD

**Issue by TobiaszCudnik** [bterlson/strict-event-emitter-types#2]
Thanks for all the hacking and the npm module to bring typed emitters to the masses in a clean and easy way.

I was happy to abandon the property-overriding-a-method trick which worked for the same purpose in TS prior to 2.8, but whats obviously missing is the **support for more than one parameter** passed to the listener.

I tried using an array for typing, but no luck. This is what I see in VS Code
![screen shot 2018-05-17 at 6 28 19 pm](https://user-images.githubusercontent.com/93027/40206990-392318ec-5a00-11e8-99ca-57cf8958a68f.png)

Any way to overcome this limitation? Thanks!

**Comment by bterlson** [comment]
@TobiaszCudnik Sorry I missed this bug a while back!

I think this is not possible at the moment, TypeScript needs more support for mapping between tuples and arguments lists. I think we have something in the pipe that will help.... stay tuned.

**Comment by bterlson** [comment]
@TobiaszCudnik Good news, once https://github.com/Microsoft/TypeScript/pull/24897 lands we will have what we need to implement this.

However, I wonder... would you prefer tuples be lifted to arguments lists as you propose? Or, would you prefer extracting event payloads from an argument list? It might look like:

```ts
interface Events {
  test: (a: number, b: string) => void;
}
```

This has the advantage of giving you a name for your parameters. I could also conceivably support both patterns, but having the tuple mean a multi-arg event means events which emit tuples need extra wrapping, e.g.

```ts
interface TupleEvents {
  test: [[number, string]];
}
```

Let me know any thoughts :)

**Comment by TobiaszCudnik** [comment]
@bterlson Great to hear you've finally figured out tuples-to-params in TS, been waiting for years for properly typed call/apply :)

Regarding the preferences of args lists vs tuples I'm definitely on the args lists side, as its natural and as you mentioned gives you param names. It also gives you the return value, which not common for emitters, does apply (eg in my case it can optionally be a boolean causing cancellation).

Here's how I've been [typing my emitters so far](https://github.com/TobiaszCudnik/gtd-bot/blob/master/typings/machines/google/gmail/sync.ts#L15) (generated code):
```
export interface IBind extends IBindBase {
  (
    event: 'Enabled_enter',
    // return is significant for this event
    listener: () => boolean | undefined,
    context?: Object
  ): this
  (
    event: 'Enabled_state',
    // for this event, the return doesn't matter
    listener: () => any,
    context?: Object
  ): this
}

export interface IEmit extends IEmitBase {
  (event: 'Enabled_enter'): boolean | void
  (event: 'Enabled_state'): boolean | void
}
```

The reason why this works can be [found here](https://github.com/TobiaszCudnik/asyncmachine/blob/master/src/asyncmachine.ts#L1589) - it's overloading emit/on with an interface with call signatures.

Fortunately with conditional types we dont have to duplicate the args lists, as they can be extracted. It would be cool to be able to type the returns of the `on/once/emit` methods though.

Thanks!

**Comment by bterlson** [comment]
@TobiaszCudnik `master` has support for this now except handlers must return void. I'll work on fixing that after a major refactoring I want to attempt.

**Comment by bterlson** [comment]
This is in 2.0!
