### ISSUE TITLE
TS 2.9 support

### ISSUE THREAD

**Issue by paulmelnikow** [bterlson/strict-event-emitter-types#4]
Hi, I noticed the note in the readme about the TS 3.0 requirement.

Is there an earlier release which supports 2.9?

Thanks!

**Comment by bterlson** [comment]
Gah sorry for the delay. The version on NPM only needs TS 2.8 (see also the [readme on npm](https://www.npmjs.com/package/strict-event-emitter-types)).

The next version which supports events with multiple arguments probably will require TS 3.1 (although I'm investigating workarounds to make it work in 3.0; what's in master is a work in progress).

I need to be better about feature branches so this is more clear :)

**Comment by bterlson** [comment]
I won't be able to support TS < 3.1, unfortunately. But hopefully it's not an issue now.
