### ISSUE TITLE
Allow other return types of the event handlers than void

### ISSUE THREAD

**Issue by Ulrikop** [bterlson/strict-event-emitter-types#7]
I like the idea of the `StrictEventEmitter` that it should work with any kind of `EventEmitter`. But because it only supports `void` as return value of an event handlers, I can't use it for example for a own implementation of a `EventEmitter` which works with asynchronous handlers (for example to execute the handlers in an ordered way or to `await` the `emit` call).

Could the `StrictEventEmitter` be adapt so that the return value of the event handler can be customized?

**Comment by bterlson** [comment]
I only intend to support Node's event emitter with this library. There are very many modifications to base event emitters that people do, and supporting all of them would be very difficult. You can always copy these types into your program as customize as you need!
